version: '3.8'

services:
  # Infrastructure Services
  zookeeper:
    extends:
      file: ./Infras/kafka/docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: ./Infras/kafka/docker-compose.yml
      service: kafka

  kafka-init:
    extends:
      file: ./Infras/kafka/docker-compose.yml
      service: kafka-init

  kafka-ui:
    extends:
      file: ./Infras/kafka/docker-compose.yml
      service: kafka-ui

  redis:
    extends:
      file: ./Infras/redis/docker-compose.yml
      service: redis

  postgres:
    image: postgres:17
    environment:
      - POSTGRES_DB=UserServiceDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network
    restart: unless-stopped

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  redis-data:
  postgres-data:

networks:
  microservices-network:
    driver: bridge 