version: '3.8'

services:
  # Include Kafka infrastructure
  zookeeper:
    extends:
      file: ./Infras/kafka/docker-compose.yml
      service: zookeeper

  kafka:
    extends:
      file: ./Infras/kafka/docker-compose.yml
      service: kafka

  kafka-init:
    extends:
      file: ./Infras/kafka/docker-compose.yml
      service: kafka-init

  kafka-ui:
    extends:
      file: ./Infras/kafka/docker-compose.yml
      service: kafka-ui

  # Include Redis
  redis:
    extends:
      file: ./Infras/redis/docker-compose.yml
      service: redis

  # Include PostgreSQL
  # postgres:
  #   extends:
  #     file: ./Infras/postgres/docker-compose.yml
  #     service: postgres

volumes:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  redis-data:
  postgres-data: 